version: 2

project_name: caddy

before:
  hooks:
    - go mod tidy

builds:
  - id: binary
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      # ARM builds only for Linux
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    # Enable replacement of builds with ids (v2.8 change) although not explicitly using multiple builds here
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

nfpms:
  - id: caddy-deb
    package_name: caddy
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    vendor: "Custom Build"
    homepage: "https://github.com/crazyuploader/caddy"
    maintainer: "Jugal Kishore"
    description: |
      Caddy Web Server with custom plugins.
      Includes: cloudflare-dns, redis-storage, postgres-storage, cf-kv-storage, brotli, rate-limit
    license: "MIT"
    section: web
    priority: optional
    provides:
      - httpd
    replaces:
      - caddy
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      # Config directory
      - dst: /etc/caddy
        type: dir
        file_info:
          mode: 0755
      # Data directory
      - dst: /var/lib/caddy
        type: dir
        file_info:
          mode: 0755
      - src: ./systemd/caddy.service
        dst: /lib/systemd/system/caddy.service
        file_info:
          mode: 0644
          owner: root
          group: root
      - src: ./systemd/caddy-api.service
        dst: /lib/systemd/system/caddy-api.service
        file_info:
          mode: 0644
          owner: root
          group: root
    dependencies:
      - ca-certificates
    recommends:
      - systemd
    scripts:
      preinstall: ./scripts/preinstall.sh
      postinstall: ./scripts/postinstall.sh
      preremove: ./scripts/preremove.sh
      postremove: ./scripts/postremove.sh
    mtime: "{{ .CommitDate }}"
    deb:
      fields:
        Bugs: https://github.com/crazyuploader/caddy/issues
    rpm:
      group: System Environment/Daemons
      summary: Caddy Web Server with custom plugins
    apk:
      scripts:
        preupgrade: ./scripts/preinstall.sh
        postupgrade: ./scripts/postinstall.sh

dockers_v2:
  - images:
      - "ghcr.io/crazyuploader/caddy"
    tags:
      - "latest"
      - "{{ .Version }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    # Disable during snapshot builds (CI) since manifest lists cannot be created without pushing
    disable: "{{ .IsSnapshot }}"
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Caddy Web Server with custom plugins"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.licenses": "Apache-2.0"

release:
  github:
    owner: crazyuploader
    name: caddy
  draft: false
  prerelease: auto
  header: |
    ## Custom Caddy Build

    ### Included Plugins
    - dns.providers.cloudflare
    - caddy.storage.redis
    - caddy.storage.postgres
    - caddy.storage.cloudflare_kv
    - http.encoders.br
    - http.handlers.rate_limit

    ### Installation via APT
    See [installation instructions](https://caddy.devjugal.com)

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--yes"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
    artifacts: all

checksum:
  name_template: "checksums.txt"
  algorithm: sha512
