version: 2

project_name: caddy

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'github.com/caddyserver/caddy/v2.CustomVersion={{ .Version }}'

archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

nfpms:
  - id: caddy-deb
    package_name: caddy
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    vendor: "Custom Build"
    homepage: "https://github.com/crazyuploader/caddy"
    maintainer: "Jugal Kishore"
    description: |
      Caddy Web Server with custom plugins.
      Includes: cloudflare-dns, redis-storage, postgres-storage, cf-kv-storage, brotli, rate-limit
    license: "MIT"
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: ./systemd/caddy.service
        dst: /lib/systemd/system/caddy.service
        file_info:
          mode: 0644
          owner: root
          group: root
      - src: ./systemd/caddy-api.service
        dst: /lib/systemd/system/caddy-api.service
        file_info:
          mode: 0644
          owner: root
          group: root
      - src: ./public/index.html
        dst: /usr/share/caddy/index.html
        file_info:
          mode: 0644
          owner: root
          group: root
    dependencies:
      - ca-certificates
    recommends:
      - systemd

dockers:
  # AMD64
  - image_templates:
      - "ghcr.io/crazyuploader/caddy:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"

  # ARM64
  - image_templates:
      - "ghcr.io/crazyuploader/caddy:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"

  # ARMv7
  - image_templates:
      - "ghcr.io/crazyuploader/caddy:{{ .Version }}-armv7"
    use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"

docker_manifests:
  - name_template: "ghcr.io/crazyuploader/caddy:{{ .Version }}"
    image_templates:
      - "ghcr.io/crazyuploader/caddy:{{ .Version }}-amd64"
      - "ghcr.io/crazyuploader/caddy:{{ .Version }}-arm64"
      - "ghcr.io/crazyuploader/caddy:{{ .Version }}-armv7"
  - name_template: "ghcr.io/crazyuploader/caddy:latest"
    image_templates:
      - "ghcr.io/crazyuploader/caddy:{{ .Version }}-amd64"
      - "ghcr.io/crazyuploader/caddy:{{ .Version }}-arm64"
      - "ghcr.io/crazyuploader/caddy:{{ .Version }}-armv7"

release:
  github:
    owner: crazyuploader
    name: caddy
  draft: false
  prerelease: auto
  header: |
    ## Custom Caddy Build

    ### Included Plugins
    - dns.providers.cloudflare
    - caddy.storage.redis
    - caddy.storage.postgres
    - caddy.storage.cloudflare_kv
    - http.encoders.br
    - http.handlers.rate_limit

    ### Installation via APT
    See [installation instructions](https://caddy.devjugal.com)

checksum:
  name_template: "checksums.txt"
